package sistemastock.model;
// Generated Aug 2, 2016 6:30:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private String id;
     private Categorias categorias;
     private Marcas marcas;
     private Ubicaciones ubicaciones;
     private String nombre;
     private Set distribuidoreses = new HashSet(0);

    public Productos() {
    }

	
    public Productos(String id, Categorias categorias, Marcas marcas, Ubicaciones ubicaciones) {
        this.id = id;
        this.categorias = categorias;
        this.marcas = marcas;
        this.ubicaciones = ubicaciones;
    }
    public Productos(String id, Categorias categorias, Marcas marcas, Ubicaciones ubicaciones, String nombre, Set distribuidoreses) {
       this.id = id;
       this.categorias = categorias;
       this.marcas = marcas;
       this.ubicaciones = ubicaciones;
       this.nombre = nombre;
       this.distribuidoreses = distribuidoreses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Marcas getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Marcas marcas) {
        this.marcas = marcas;
    }
    public Ubicaciones getUbicaciones() {
        return this.ubicaciones;
    }
    
    public void setUbicaciones(Ubicaciones ubicaciones) {
        this.ubicaciones = ubicaciones;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDistribuidoreses() {
        return this.distribuidoreses;
    }
    
    public void setDistribuidoreses(Set distribuidoreses) {
        this.distribuidoreses = distribuidoreses;
    }




}


