package sistemastock.model;
// Generated Jul 7, 2016 7:40:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
//import org.hibernate.annotations.Entity;
//import org.hibernate.annotations.Table;
//import org.hibernate.cfg.AccessType;



import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
/**StringProperty
 * Ubicaciones generated by hbm2java
 */

@Entity
public class Ubicaciones  implements java.io.Serializable {


     private final StringProperty id = new SimpleStringProperty(this, "id");

     private final StringProperty pasillo = new SimpleStringProperty(this, "pasillo");
     private final StringProperty estante = new SimpleStringProperty(this, "estante");
     private final IntegerProperty repisa = new SimpleIntegerProperty(this, "repisa");
     private Set productoses = new HashSet(0);

    public Ubicaciones() {
    }

	
    public Ubicaciones(String  id) {
        this.id.set(id);
    }
    public Ubicaciones(String id, String pasillo, String estante, Integer repisa, Set productoses) {
       this.id.set(id);
       this.pasillo.set(pasillo);
       this.estante.set(estante);
       this.repisa.set(repisa);
       this.productoses = productoses;
    }
   
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="id")
    public String getId() {
        return this.id.get();
    }
    
    public void setId(String id) {
        this.id.set(id);
    }
    
    public StringProperty idProperty(){
        return id;
    }
    
    @Column(name="pasillo")
    public String getPasillo() {
        return this.pasillo.get();
    }
    
    public void setPasillo(String pasillo) {
       
            this.pasillo.set(pasillo);
    }
    
    public StringProperty pasilloProperty(){
        return this.pasillo;
    }
    
    
    @Column(name="estante")
    public String getEstante() {
        return this.estante.get();
    }
    
    public void setEstante(String estante) {
        this.estante.set(estante);
    }
    public StringProperty estanteProperty(){
        return this.estante;
    }
    
    
    @Column(name="repisa")
    public Integer getRepisa() {
        return this.repisa.get();
    }
        
    public void setRepisa(Integer repisa) {
       this.repisa.set(repisa);
    }
    public Set getProductoses() {
        return this.productoses;
    }
    public IntegerProperty repisaProperty(){
        return this.repisa;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }

    private boolean validarEstante(){
        if(getEstante().matches("[a-zA-Z]*"))
            return true;
        else
            return false;
        
    }
    
    private boolean validarRepisa(){
        if(getEstante().matches("\\d*"))
            return true;
        else
            return false;
        
    }
    
    private boolean validarPasillo(){
        if(getEstante().matches("[a-zA-Z]*"))
            return true;
        else
            return false;
        
    }

}


